DjangoProject1/urls.py
from itertools import product

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import blog, contact,about


app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
]

shop/urls.py
from django.urls import path
from .views import product_list, product_detail


app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', product_detail, name='product_detail'),
]

templates/includes/footer_navigation.html
<nav id="site-navigation">
                <button class="menu-toggle" aria-controls="primary-menu" aria-expanded="false">Primary Menu</button>
                    <div class="menu-%e3%83%95%e3%83%83%e3%82%bf%e3%83%bc-container"><ul id="primary-menu" class="menu"><li id="menu-item-4821" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4821"><a href="{% url 'blog:about' %}">
О НАС</a></li>

</li>
<li id="menu-item-64" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-64"><a href="{% url 'shop:product_list' %}">МАГАЗИН</a>
<ul class="sub-menu">

</ul>
</li>
<li id="menu-item-67" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-67"><a href="https://tozando.com/support/">ПОДДЕРЖКА</a>
<ul class="sub-menu">
	<li id="menu-item-68" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-68"><a href="{% url 'blog:contact' %}">Свяжитесь с нами</a></li>
	<li id="menu-item-848" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-848"><a href="{% url 'blog:contact' %}">Запрос каталога</a></li>
	<li id="menu-item-849" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-849"><a href="https://tozando.com/support/customer/">Корпоративные клиенты</a></li>
</ul>
</li>

templates/includes/navigation.html
<div class="menu-header-container">
    <ul id="primary-menu" class="menu">
        <li class="menu-item"><a href="{% url 'blog:about' %}">О НАС</a></li>
        <li class="menu-item menu-item-has-children"><a href="support">ПОДДЕРЖКА</a>
            <ul class="sub-menu">
                <li class="menu-item"><a href="{% url 'blog:contact' %}">Свяжитесь с нами</a></li>
{#                <li class="menu-item"><a href="{% url 'corporate' %}">Корпоративные клиенты</a></li>#}
            </ul>
        </li>
        <li class="menu-item"><a href="{% url 'shop:product_list' %}">МАГАЗИН</a></li>
{#        <li class="lang-item"><a href="{% url 'home_en' %}" hreflang="en-US" lang="en-US">EN</a></li>#}
    </ul>
</div>

templates/includes/sp_navigation.html
{% load i18n %}
<ul>
    <li><a href="{% url 'shop:product_list' %}">{% trans "магазин" %}</a></li>
    <li><a href="{% url 'blog:about' %}">{% trans "Блог" %}</a></li>
    <li><a href="{% url 'blog:contact' %}">{% trans "контанкты" %}</a></li>
</ul>