DjangoProject1/urls.py
from itertools import product

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import blog, contact,about


app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
]

cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/', cart_remove,
         name='cart_remove'),
]

order/urls.py
from django.urls import path
from order.views import order_create, admin_order_pdf


app_name = 'order'

urlpatterns = [
    path('admin/order/<int:order_id>/pdf/',
         admin_order_pdf, name='admin_order_pdf'),
    path('create/', order_create, name='order_create'),
]

payment/urls.py
from django.urls import path
from payment.views import (payment_canceled, payment_completed,
                           payment_process)
from payment.application.webhooks import stripe_webhook


app_name = 'payment'

urlpatterns = [
    path('process/', payment_process, name='process'),
    path('completed/', payment_completed, name='completed'),
    path('canceled/', payment_canceled, name='canceled'),
    path('webhool/', stripe_webhook, name='stripe-webhook'),
]

order/models.py
from django.db import models 
from shop.models import Product
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon
from decimal import Decimal


class Order(models.Model):
    coupon = models.ForeignKey(Coupon, related_name='orders',
                               null=True, blank=True,
                               on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0,
                                   validators=[
                                       MinValueValidator(0),
                                       MaxValueValidator(100)
                                   ])
    stripe_id = models.CharField(max_length=250, blank=True)
    first_name = models.CharField(max_length=50) 
    last_name = models.CharField(max_length=50) 
    email = models.EmailField()
    address = models.CharField(max_length=250) 
    postal_code = models.CharField(max_length=20) 
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    paid = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20)
    country = models.CharField(max_length=100)
    class Meta:
        ordering = ['-created']
        indexes = [ models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Order {self.id}'
    
    def get_total_cost(self):
        total_cost = self.get_total_cost_before_discount()
        return total_cost - self.get_discount()
    
    def get_total_cost_before_discount(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_discount(self):
        total_cost = self.get_total_cost_before_discount()
        if self.discount:
            return total_cost * (self.discount / Decimal(100))
        return Decimal(0)
    
    def get_stripe_url(self):
        if not self.stripe_id:
            # никаких ассоциированных платежей
            return ''
        if '_test_' in settings.STRIPE_SECRET_KEY:
            # путь Stripe для тестовых платежей
            path = '/test/'
        else:
            # путь Stripe для настоящих платежей
            path = '/'

        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'
    

class OrderItem(models.Model): 
    order = models.ForeignKey(Order,
        related_name='items',
        on_delete=models.CASCADE) 
    product = models.ForeignKey(Product,
        related_name='order_items',
        on_delete=models.CASCADE) 
    price = models.DecimalField(max_digits=10,
        decimal_places=2) 
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self): 
        return str(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city','phone_number', 'country']

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint

from cart.cart import Cart
from order.models import OrderItem, Order
from order.forms import OrderCreateForm
from order.tasks import order_created

def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount

            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order, product=item['product'],
                    price=item['price'], quantity=item['quantity'])
            cart.clear()
            order_created(order.id)
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm()

    return render(request, 'order/create.html',
                  {'cart': cart, 'form': form})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(
        response,
        stylesheets=[weasyprint.CSS(
            settings.STATIC_ROOT / 'css/pdf.css'
        )]
    )

    return response

templates/order/create.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Форма заказа</title>
    <style>
        body {
            background-color: #f5f5f5;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            font-family: Arial, sans-serif;
            margin: 0;
        }

        .order-card {
            background-color: #fff;
            padding: 30px;
            border-radius: 20px;
            box-shadow: 5px 5px 10px rgba(0,0,0,0.1);
            width: 320px;
        }

        .order-card h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .order-card input[type="text"],
        .order-card input[type="tel"],
        .order-card input[type="email"],
        .order-card select {
            width: 100%;
            padding: 8px;
            border: none;
            border-radius: 8px;
            background-color: #e0e0e0;
        }

        .order-card button {
            width: 48%;
            padding: 10px;
            border: none;
            border-radius: 10px;
            cursor: pointer;
        }

        .cancel-btn {
            background-color: #7EC8E3;
        }

        .submit-btn {
            background-color: #007ACC;
            color: white;
        }

        .button-group {
            display: flex;
            gap: 10px;
        }
    </style>
</head>
<body>
    <main>
        <div class="order-card">
            <h1>Оформление заказа</h1>

            <form action="{% url 'payment:process' %}" method="post">
                {% csrf_token %}

                <div class="form-group">
                    <label for="{{ form.country.id_for_label }}">Страна</label>
                    {{ form.country }}
                </div>
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                    <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
               
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Электронная почта</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label for="{{ form.city.id_for_label }}">Город</label>
                    {{ form.city }}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Адрес</label>
                    {{ form.address }}
                </div>
                <div class="form-group">
                    <label for="{{ form.postal_code.id_for_label }}">Почтовый индекс</label>
                    {{ form.postal_code }}
                </div>
                <div class="form-group">
                    <label for="{{ form.phone_number.id_for_label }}">Телефон</label>
                    {{ form.phone_number }}
                </div>

                <div class="button-group">
                    <button type="button" class="cancel-btn" onclick="window.location.href='{% url 'cart:cart_detail' %}'">Отмена</button>
                    <button type="submit" class="submit-btn">Заказать</button>
                </div>
            </form>
        </div>
    </main>
</body>
</html>

templates/order/created.html
{% extends "base.html" %}
{% block title %} Спасибо {% endblock %}

{% block content %}
    <h1>Спасибо</h1>
    <p>Ваш заказ был успешно добавлен. Номер вашего заказа <strong>{{ order.id }}</strong>.</p>
{% endblock %}

templates/order/pdf.html
<html> 
<body>
<h1 >My Shop</h1> 
<p>Invoice no. {{ order.id }}<br> 
    <span class="secondary">{{ order.created|date:"M d, Y" }}</span> 
</p>
<h3>Bill to</h3> 
<p>
    {{ order.first_name }} {{ order.last_name }}<br> 
    {{ order.email }}<br>
    {{ order.address }}<br>
    {{ order.postal_code }}, {{ order.city }}
</p>
<h3>Items bought</h3> 
<table>
    <thead> 
        <tr>
            <th>Product</th> 
            <th>Price</th> 
            <th>Quantity</th>
            <th>Cost</th> 
            </tr>
    </thead> 
    <tbody>
    {% for item in order.items.all %} 
        <tr class="row{% cycle "1" "2" %}">
            <td>{{ item.product.name }}</td>
            <td class="num">${{ item.price }}</td> 
            <td class="num">{{ item.quantity }}</td> 
            <td class="num">${{ item.get_cost }}</td>
        </tr>
    {% endfor %}
        <tr class="total">
            <td colspan="3">Total</td>
            <td class="num">${{ order.get_total_cost }}</td>
        </tr>
    </tbody> 
</table>
    <span class="{% if order.paid %}paid{% else %}pending{% endif %}"> 
    {% if order.paid %}Paid{% else %}Pending payment{% endif %}
</span> 
</body>
</html>